version: "3.1"

services:
  db2:
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: ejemplo
    ports:
      - 3308:3308
  web2:
    image: nginx
    restart: always
    ports:
      - 8082:8082
    volumes:
      - ./html:/usr/share/nginx/html
  db3:
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: ejemplo
    ports:
      - 3309:3309
  web3:
    image: nginx
    restart: always
    ports:
      - 8083:8083
    volumes:
      - ./html2:/usr/share/nginx/html
