version: "3.1"

services:
  db1:
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: ejemplo
    ports:
      - 3307:3307
  web1:
    image: nginx
    restart: always
    ports:
      - 8081:8081
    volumes:
      - ./html:/usr/share/nginx/html